apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: lldap-pvc
    app.kubernetes.io/name: lldap-pvc
  name: lldap-data
  namespace: auth
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
