apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  namespace: auth
spec:
  selector:
    matchLabels:
      app: authelia
  replicas: 1
  template:
    metadata:
      labels:
        app: authelia
    spec:
      containers:
      - name: authelia
        image: authelia/authelia:latest
        ports:
        - containerPort: 9091
          name: http
        volumeMounts:
        - name: config
          mountPath: /config
        - name: data
          mountPath: /data
      volumes:
      - name: config
        configMap:
          name: authelia-config
      - name: data
        persistentVolumeClaim:
          claimName: authelia-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: authelia-service
  namespace: auth
spec:
  selector:
    app: authelia
  ports:
  - name: http
    port: 9091
    targetPort: 9091
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authelia-ingress
  namespace: auth
  annotations:
    spec.ingressClassName: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - host: auth.picklemustard.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: authelia-service
            port:
              number: 9091
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-data-pvc
  namespace: auth
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
  namespace: auth
data:
  configuration.yml: |
    host: 0.0.0.0
    port: 9091
    log_level: info
    jwt_secret: K6hRikBb0Y0rrMpuWntvPnD+S/yDfm64DTi5g9zs39s=

      #default_redirection_url: https://auth.andromeda.picklemustard.dev

    authentication_backend:
      ldap:
        url: ldap://lldap-service.auth.svc.cluster.local:3890
        base_dn: dc=andromeda,dc=picklemustard,dc=dev
        user: uid=bind_reader,ou=people,dc=andromeda,dc=picklemustard,dc=dev
        password: purple14735# 
        additional_users_dn: ou=people
        users_filter: (&({username_attribute}={input})(objectClass=person))
        groups_filter: (&(member={dn})(objectClass=groupOfNames))
        username_attribute: uid
        mail_attribute: mail
        display_name_attribute: displayName
        group_name_attribute: cn

    access_control:
      default_policy: deny
      rules:
        - domain: "*.andromeda.picklemustard.dev"
          policy: bypass

    session:
      name: 'authelia_session'
      same_site: 'lax'
      remember_me: '1M'
      expiration: '1h'  # 1 hour
      inactivity: '5m'   # 5 minutes
      cookies:
        - domain: 'picklemustard.dev'
          authelia_url: 'https://auth.andromeda.picklemustard.dev'
            #default_redirection_url: 'https://andromeda.picklemustard.dev'
          name: 'authelia_session'
          same_site: 'lax'
          inactivity: '5m'
          expiration: '1h'
          remember_me: '1d'

    regulation:
      max_retries: 3
      find_time: 120
      ban_time: 300

    storage:
      encryption_key: nBNfNr0Risq/iXUFCwu8RBiqpPhcPVFFcZQiTOX3R1A=
      local:
        path: /data/db.sqlite3

    notifier:
      filesystem:
        filename: /data/notification.txt
