apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-

    tlsStore:
      default:
        defaultCertificate:
          secretName: picklemustard-dev-tls

    ports:
      web:
        forwardedHeaders:
          insecure: true
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        forwardedHeaders:
          insecure: true
    logs:
      level: DEBUG
      access:
        enabled: true
    #service:
    #  spec:
    #    externalTrafficPolicy: Local

    dashboard:
      enabled: true
      insecure: true

    deployment:
      kind: DaemonSet
    hostNetwork: true

    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 2
        maxSurge:

    additionalArguments:
      - "--entryPoints.ldap.address=:3890/tcp"
      - "--entryPoints.imaps.address=:10993/tcp"
      - "--entryPoints.pop3s.address=:10995/tcp"
      - "--entryPoints.smtp.address=:10025/tcp"
      - "--entryPoints.smtps.address=:10465/tcp"
      - "--serversTransport.insecureSkipVerify=true"
      - "--entryPoints.websecure.http.tls=true"
      - "--api"
      - "--api.dashboard=true"
      - "--api.insecure=true"

# See https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml for more examples
# The deployment.kind=DaemonSet and hostNetwork=true is to get real ip and x-forwarded for,
# and can be omitted if this is not needed.

# The updateStrategy settings are required for the latest traefik helm version when using hostNetwork.
# see more here: https://github.com/traefik/traefik-helm-chart/blob/v20.8.0/traefik/templates/daemonset.yaml#L12-L14
# but this version not yet supported by k3s, so leaving it commented out for now.
# The config above has been tested to work with latest stable k3s (v1.25.4+k3s1).
