apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: picklemustard-dev
  namespace: kube-system
spec:
  secretName: picklemustard-dev-tls
  commonName: "*.picklemustard.dev"
  dnsNames:
    - "picklemustard.dev"
    - "*.picklemustard.dev"
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
