apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: media-data
  namespace: media
provisioner: smb.csi.k8s.io
parameters:
  source: //192.168.1.77/Visual_Media
  csi.storage.k8s.io/provisioner-secret-name: media-data-creds
  csi.storage.k8s.io/provisioner-secret-namespace: media
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
