apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: sonarr-service
    app.kubernetes.io/name: sonarr-service
  name: sonarr-service
  namespace: media 
spec:
  ports:
    - name: "8989"
      port: 8989 
      targetPort: 8989 
  selector:
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/name: sonarr
