apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  creationTimestamp: '2025-05-14T00:08:55Z'
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: media-data
    app.kubernetes.io/name: media-data 
    app.kubernetes.io/version: 0.12.1
  name: media-data 
  namespace: media 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: media-data
  storageClassName: smb
