apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: picklemustard-dev-authelia
  namespace: auth
spec:
  secretName: picklemustard-dev-tls-authelia
  commonName: "*.picklemustard.dev"
  dnsNames:
    - "picklemustard.dev"
    - "*.picklemustard.dev"
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
