apiVersion: v1
kind: Service
metadata:
  name: authelia-service
  namespace: lldap
spec:
  type: NodePort
  sessionAffinity: None
    #clusterIP: 10.43.181.178
    #clusterIPs:
    #  - 10.43.181.177
  internalTrafficPolicy: Cluster
  externalTrafficPolicy: Local
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/name: authelia
  ports:
  - name: http
    port: 9091
    protocol: TCP
    targetPort: 9091
