apiVersion: v1
kind: Service
metadata:
  name: authelia-service
  namespace: auth
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9091"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  sessionAffinity: None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/name: authelia
  ports:
  - name: http
    port: 9091
    protocol: TCP
    targetPort: 9091
