apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: forgejo
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: forgejo
  namespaceSelector:
    matchNames:
      - git
  endpoints:
    - port: "3000"
      interval: 30s
      path: /metrics
