apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jellyfin
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: jellyfin
  namespaceSelector:
    matchNames:
      - media
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
