apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vaultwarden
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vaultwarden
  namespaceSelector:
    matchNames:
      - vaultwarden
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
