apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data-pvc
  namespace: minecraft
  labels:
    app.kubernetes.io/instance: mc-server-neoforge
    app.kubernetes.io/name: minecraft-data-pvc
spec:
  storageClassName: local-path
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
