apiVersion: v1
kind: PersistentVolume
metadata:
  name: documents-nfs-pv
spec:
  capacity: 
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
  nfs:
    server: 192.168.200.205
    path: /mnt/general-pool/media/documents
