apiVersion: apps/v1
kind: Deployment
metadata:
  name: pterodactyl
  labels:
    app.kubernetes.io/instance: pterodactyl-panel
    app.kubernetes.io/name: pterodactyl-panel
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: pterodactyl-panel
      app.kubernetes.io/name: pterodactyl-panel
  replicas: 1
  strategy: 
    type: Recreate
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: pterodactyl-panel
        app.kubernetes.io/name: pterodactyl-panel
      annotations:
        deploy-date: "deploy-date-value"
    spec:
      containers:
      - name: pterodactyl
        image: ghcr.io/pterodactyl/panel:latest

