apiVersion: apps/v1
kind: Deployment
metadata:
  name: openproject
  namespace: collab
  labels:
    app.kubernetes.io/instance: openproject
    app.kubernetes.io/name: openproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: openproject
      app.kubernetes.io/name: openproject
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: openproject
        app.kubernetes.io/name: openproject
    spec:
      initContainers:
        - name: migrate
          image: openproject/openproject:17-slim
          imagePullPolicy: IfNotPresent
          command: ["/app/bin/setup"]
          env:
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: openproject-secrets
                  key: secret-key-base
            - name: DATABASE_URL
              value: "postgresql://postgres-postgresql.postgres.svc.cluster.local:5432/openproject"
            - name: OPENPROJECT_DB_USERNAME
              value: "postgres_fid"
            - name: OPENPROJECT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openproject-secrets
                  key: postgres-password
            - name: OPENPROJECT_HOST__NAME
              valueFrom:
                configMapKeyRef:
                  name: openproject-config
                  key: OPENPROJECT_HOST__NAME
            - name: OPENPROJECT_HTTPS
              valueFrom:
                configMapKeyRef:
                  name: openproject-config
                  key: OPENPROJECT_HTTPS
            - name: OPENPROJECT_RAILS__RELATIVE__URL__ROOT
              valueFrom:
                configMapKeyRef:
                  name: openproject-config
                  key: OPENPROJECT_RAILS__RELATIVE__URL__ROOT
            - name: OPENPROJECT_SEED_ADMIN_USER_NAME
              valueFrom:
                configMapKeyRef:
                  name: openproject-config
                  key: OPENPROJECT_SEED__ADMIN__USER__NAME
            - name: OPENPROJECT_SEED_ADMIN_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openproject-secrets
                  key: admin-password
            - name: OPENPROJECT_SEED_ADMIN_USER_MAIL
              value: "endmin@picklemustard.dev"
            - name: OPENPROJECT_SEED_ADMIN_USER_PASSWORD_RESET
              value: "true"
      containers:
        - name: openproject
          image: openproject/openproject:17-slim
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: OPENPROJECT_WEB_WORKERS
              value: "1"
            - name: OPENPROJECT_HTTPS
              value: "false"
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: openproject-secrets
                  key: secret-key-base
            - name: OPENPROJECT_HOST__NAME
              valueFrom:
                configMapKeyRef:
                  name: openproject-config
                  key: OPENPROJECT_HOST__NAME
            - name: OPENPROJECT_HTTPS
              valueFrom:
                configMapKeyRef:
                  name: openproject-config
                  key: OPENPROJECT_HTTPS
            - name: OPENPROJECT_RAILS__RELATIVE__URL__ROOT
              valueFrom:
                configMapKeyRef:
                  name: openproject-config
                  key: OPENPROJECT_RAILS__RELATIVE__URL__ROOT
            - name: OPENPROJECT_DEFAULT__LANGUAGE
              valueFrom:
                configMapKeyRef:
                  name: openproject-config
                  key: OPENPROJECT_DEFAULT__LANGUAGE
            - name: DATABASE_URL
              value: "postgres://postgres-postgresql.postgres.svc.cluster.local:5432/openproject"
            - name: OPENPROJECT_DB_USERNAME
              value: "postgres_fid"
            - name: OPENPROJECT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openproject-secrets
                  key: postgres-password
            - name: OPENPROJECT_SEED__ADMIN__USER__NAME
              valueFrom:
                configMapKeyRef:
                  name: openproject-config
                  key: OPENPROJECT_SEED__ADMIN__USER__NAME
            - name: OPENPROJECT_SEED__ADMIN__USER__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openproject-secrets
                  key: admin-password
            - name: OPENPROJECT_SEED__ADMIN__USER__MAIL
              value: "endmin@picklemustard.dev"
          volumeMounts:
            - mountPath: /var/openproject/assets
              name: openproject-data
              subPath: assets
            - mountPath: /var/openproject/files
              name: openproject-data
              subPath: files
      restartPolicy: Always
      volumes:
        - name: openproject-data
          persistentVolumeClaim:
            claimName: openproject-data
