apiVersion: batch/v1
kind: Job
metadata:
  name: openproject-migration
  namespace: collab
  labels:
    app.kubernetes.io/instance: openproject-migration
    app.kubernetes.io/name: openproject-migration
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: openproject-migration
        app.kubernetes.io/name: openproject-migration
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: openproject/openproject:16-slim
          imagePullPolicy: IfNotPresent
          command: ["./bin/rake", "db:migrate", "RAILS_ENV=production"]
          env:
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: openproject-secrets
                  key: secret-key-base
            - name: OPENPROJECT_HOST__NAME
              valueFrom:
                configMapKeyRef:
                  name: openproject-config
                  key: OPENPROJECT_HOST__NAME
            - name: OPENPROJECT_HTTPS
              valueFrom:
                configMapKeyRef:
                  name: openproject-config
                  key: OPENPROJECT_HTTPS
            - name: OPENPROJECT_RAILS__RELATIVE__URL__ROOT
              valueFrom:
                configMapKeyRef:
                  name: openproject-config
                  key: OPENPROJECT_RAILS__RELATIVE__URL__ROOT
            - name: OPENPROJECT_DEFAULT__LANGUAGE
              valueFrom:
                configMapKeyRef:
                  name: openproject-config
                  key: OPENPROJECT_DEFAULT__LANGUAGE
            - name: DATABASE_URL
              value: "postgres://postgres-postgresql.postgres.svc.cluster.local:5432/openproject"
            - name: OPENPROJECT_DB_USERNAME
              value: "postgres_fid"
            - name: OPENPROJECT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openproject-secrets
                  key: postgres-password
            - name: OPENPROJECT__LDAP__HOST
              valueFrom:
                configMapKeyRef:
                  name: openproject-config
                  key: OPENPROJECT__LDAP__HOST
            - name: OPENPROJECT__LDAP__PORT
              valueFrom:
                configMapKeyRef:
                  name: openproject-config
                  key: OPENPROJECT__LDAP__PORT
            - name: OPENPROJECT__LDAP__BASE
              valueFrom:
                configMapKeyRef:
                  name: openproject-config
                  key: OPENPROJECT__LDAP__BASE
            - name: OPENPROJECT__LDAP__BIND__DN
              valueFrom:
                configMapKeyRef:
                  name: openproject-config
                  key: OPENPROJECT__LDAP__BIND__DN
            - name: OPENPROJECT__LDAP__BIND__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openproject-secrets
                  key: ldap-password
            - name: OPENPROJECT__LDAP__ATTRIBUTE__LOGIN
              valueFrom:
                configMapKeyRef:
                  name: openproject-config
                  key: OPENPROJECT__LDAP__ATTRIBUTE__LOGIN
            - name: OPENPROJECT__LDAP__ATTRIBUTE__FIRSTNAME
              valueFrom:
                configMapKeyRef:
                  name: openproject-config
                  key: OPENPROJECT__LDAP__ATTRIBUTE__FIRSTNAME
            - name: OPENPROJECT__LDAP__ATTRIBUTE__LASTNAME
              valueFrom:
                configMapKeyRef:
                  name: openproject-config
                  key: OPENPROJECT__LDAP__ATTRIBUTE__LASTNAME
            - name: OPENPROJECT__LDAP__ATTRIBUTE__EMAIL
              valueFrom:
                configMapKeyRef:
                  name: openproject-config
                  key: OPENPROJECT__LDAP__ATTRIBUTE__EMAIL
            - name: OPENPROJECT__LDAP__VERIFY__PEER
              valueFrom:
                configMapKeyRef:
                  name: openproject-config
                  key: OPENPROJECT__LDAP__VERIFY__PEER
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
