apiVersion: v1
kind: Secret
metadata:
  name: openproject-secrets
  namespace: collab
type: Opaque
stringData:
  secret-key-base: "***REMOVED***"
  postgres-password: "***REMOVED***"
  ldap-password: "***REMOVED***"
