apiVersion: v1
kind: ConfigMap
metadata:
  name: openproject-config
  namespace: collab
  labels:
    app.kubernetes.io/instance: openproject-config
    app.kubernetes.io/name: openproject-config
data:
  OPENPROJECT_HOST__NAME: "andromeda.picklemustard.dev"
  OPENPROJECT_HTTPS: "false"
  OPENPROJECT_RAILS__RELATIVE__URL__ROOT: "/collab/plan"
  OPENPROJECT_DEFAULT__LANGUAGE: "en"
  OPENPROJECT_SEED__ADMIN__USER__NAME: "endmin"
