apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openproject
  namespace: collab
  labels:
    app.kubernetes.io/instance: openproject
    app.kubernetes.io/name: openproject
spec:
  storageClassName: smb
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
