apiVersion: v1
king: configmap
metadata:
  labels:
    app.kubernetes.io/instance: vaultwarden-ldap
    app.kubernetes.io/name: vaultwarden-ldap
    app.kubernetes.io/version: latest
  name: vaultwarden-ldap
  namespace: vaultwarden
data:
  config.toml: |
    vaultwarden_url = "https://vault.picklemustard.dev"
    ldap_host = "ldap://192.168.1.142:3890"
    ldap_bind_dn = "uid=bind_reader,ou=people-dc=andromeda,dc=picklemustard,dc=dev"
    ldap_search_base_dn = "dc=andromeda,dc=picklemustard,dc=dev"
    ldap_search_filter = "(&(objectClass
