apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: jellyfin-data
    app.kubernetes.io/name: jellyfin-data
  name: jellyfin-data
  namespace: media 
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
