apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-smbplugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-smbplugin
  template:
    metadata:
      labels:
        app: csi-smbplugin
    spec:
      serviceAccountName: csi-smb-node-sa
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: liveness-probe
          imagePullPolicy: IfNotPresent
          image: registry.k8s.io/sig-storage/livenessprobe:v2.11.0
          args:
            - --csi-address=$(ADDRESS)
            - --probe-timeout=3s
            - --health-port=29643
            - --v=2
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - name: node-driver-registrar
          imagePullPolicy: IfNotPresent
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.9.0
          args:
            - --csi-address=$(ADDRESS)
            - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
            - --v=2
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/pods/??/volumes/kubernetes.io~csi/smb.csi.k8s.io*/mount.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: smb
          imagePullPolicy: IfNotPresent
          image: mcr.microsoft.com/k8s/csi/smb-csi:v1.11.0
          args:
            - --v=5
            - --nodeid=$(NODE_ID)
            - --endpoint=$(CSI_ENDPOINT)
            - --metrics-address=0.0.0.0:29643
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
          ports:
            - containerPort: 29643
              name: healthz
              protocol: TCP
            - containerPort: 29645
              name: metrics
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 30
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
              name: mountpoint-dir
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smb-csi-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smb-csi-controller
  template:
    metadata:
      labels:
        app: smb-csi-controller
    spec:
      serviceAccountName: csi-smb-controller-sa
      containers:
        - name: csi-provisioner
          imagePullPolicy: IfNotPresent
          image: registry.k8s.io/sig-storage/csi-provisioner:v4.0.0
          args:
            - --csi-address=$(ADDRESS)
            - --leader-election
            - --leader-election-namespace=kube-system
            - --timeout=300s
            - --extra-create-metadata
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: liveness-probe
          imagePullPolicy: IfNotPresent
          image: registry.k8s.io/sig-storage/livenessprobe:v2.11.0
          args:
            - --csi-address=$(ADDRESS)
            - --probe-timeout=3s
            - --health-port=29642
            - --v=2
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: smb
          imagePullPolicy: IfNotPresent
          image: mcr.microsoft.com/k8s/csi/smb-csi:v1.11.0
          args:
            - --v=5
            - --nodeid=$(NODE_ID)
            - --endpoint=$(CSI_ENDPOINT)
            - --metrics-address=0.0.0.0:29642
          env:
            - name: NODE_ID
              value: "controller"
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
          ports:
            - containerPort: 29642
              name: healthz
              protocol: TCP
            - containerPort: 29644
              name: metrics
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 30
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir: {}
