apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-smb-controller-sa
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-smb-node-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smb-secret-provisioner-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: smb-secret-provisioner-rolebinding
subjects:
  - kind: ServiceAccount
    name: csi-smb-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: smb-secret-provisioner-role
  apiGroup: rbac.authorization.k8s.io
