apiVersion: v1
kind: Secret
metadata:
  name: media-data-creds
  namespace: media
type: Opaque
stringData:
  username: "YOUR_SMB_USERNAME"
  password: "YOUR_SMB_PASSWORD"
  domain: ""  # Optional: leave empty if not using a domain
