apiVersion: shulkermc.io/v1alpha1
kind: MinecraftCluster
metadata:
  name: basecluster
  namespace: minecraft
  labels:
    app.kubernetes.io/name: minecraftcluster
    app.kubernetes.io/instance: minecraftcluster
spec:
  redis:
    provided: 
      credentialsSecretName: "redis-credentials"
      host: "redis-master.redis.svc.cluster.local"
      port: 6379
    type: Provided
