apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  creationTimestamp: '2025-05-14T00:08:55Z'
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: stalwart
    app.kubernetes.io/name: stalwart
    app.kubernetes.io/version: 0.12.1
  name: stalwart
  namespace: stalwart
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeMode: Filesystem
