apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-credentials
  namespace: postgres
type: Opaque
stringData:
  data-source-name: "postgresql://postgres:$(POSTGRES_PASSWORD)@postgres-postgresql.postgres.svc.cluster.local:5432/postgres?sslmode=disable"
