apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: redis
  labels:
    app.kubernetes.io/instance: redis-exporter
    app.kubernetes.io/name: redis-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: redis-exporter
      app.kubernetes.io/name: redis-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: redis-exporter
        app.kubernetes.io/name: redis-exporter
    spec:
      containers:
        - name: redis-exporter
          image: oliver006/redis_exporter:latest
          env:
            - name: REDIS_ADDR
              value: "redis-master:6379"
          ports:
            - containerPort: 9121
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: redis
  labels:
    app.kubernetes.io/instance: redis-exporter
    app.kubernetes.io/name: redis-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app.kubernetes.io/instance: redis-exporter
    app.kubernetes.io/name: redis-exporter
  ports:
    - name: http
      port: 9121
      targetPort: 9121
      protocol: TCP
